apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginxinc/nginx-unprivileged:stable
      ports:
        - containerPort: 80
      securityContext:
        runAsNonRoot: true # Ensures the container runs as a non-root user
        allowPrivilegeEscalation: false  # Prevents the container from gaining additional privileges
