apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: grow
      image: nginxinc/nginx-unprivileged:stable
      ports:
        - containerPort: 80
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
